const ENV_FILE_PATH = 'environments/.gym.env';
const RABBITMQ_SERVICE_NAME = 'RABBITMQ_SERVICE';
const DEFAULT_TRAINING_COUNT_LIMIT = 10;

export {
  ENV_FILE_PATH,
  RABBITMQ_SERVICE_NAME,
  DEFAULT_TRAINING_COUNT_LIMIT,
}
