### Добавление зала
POST http://localhost:4444/api/gyms
Content-Type: application/json
Authorization: Bearer

{
  "title": "Спортзал",
  "location": "Пионерская",
  "isVerified": true,
  "parameters": [1, 3],
  "description": "Подойдет для любого типа тренировок.",
  "price": 2000
}

### Получение списка залов
GET http://localhost:4444/api/gyms

### Получение зала по идентификатору
GET http://localhost:4444/api/gyms/1

### Обновление зала
PATCH http://localhost:4444/api/gyms/1
Content-Type: application/json
Authorization: Bearer

{
  "title": "Новый зал"
}

### Удаление зала
DELETE http://localhost:4444/api/gyms/2
Authorization: Bearer
